// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab2.Models;

public partial class sale
{
    public int? ProductID { get; set; }

    public string SalesmanName { get; set; }

    public int? Quantity { get; set; }
}