using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ITIEntities
{
    public class Department
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]  // This attribute indicates that the Id property is the primary key and its value will not be generated by the database (i.e., it must be set manually)
        public int DeptId { get; set; }     // Primary key for the Department entity
        [Required, MaxLength(20)]   // Data annotations for validation: DeptName is required and has a maximum length of 20 characters
        public string DeptName { get; set; }
        public int Capacity { get; set; }
        // Navigation property to the related Student entities (a department can have multiple students)  
        // Initialize the Students collection to an empty HashSet to avoid null reference issues when adding students to a department (using a HashSet ensures that each student is unique in the collection)
        public ICollection<Student> Students { get; set; } = new HashSet<Student>();
        public virtual List<Course> Courses { get; set; }
    }
}
