using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;  // Import the Entity Framework Core namespace to use DbContext and related classes
namespace ITIEntities.Data
{
    public class ITIContext : DbContext
    {
        public ITIContext()
        {
            
        }
        public ITIContext(DbContextOptions options): base(options)
        {

        }
        public DbSet<Student> Students { get; set; }   // DbSet for the Student entity, representing the Students table in the database
        public DbSet<Department> Departments { get; set; }   // DbSet for the Department entity, representing the Departments table in the database
        public DbSet<Course> Courses { get; set; }     // DbSet for the Course entity, representing the Courses table in the database
        public DbSet<StudentCourse> StudentCourses { get; set; }   // DbSet for the StudentCourse entity, representing the StudentCourses table in the database
        public DbSet<User> Users { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Course>(s =>
            {
                s.HasKey(c => c.CrsId);   // Configure CrsId as the primary key for the Course entity
                s.Property(s => s.CrsId).ValueGeneratedNever();   // Configure CrsId to be generated by the database when a new Course is added (auto-increment)
                s.Property(s => s.Name).IsRequired()
                .HasMaxLength(50);   // Configure the Name property of the Course entity to be required and have a maximum length of 50 characters
            });
            modelBuilder.Entity<StudentCourse>(s =>
            {
                s.HasKey(sc => new { sc.StudentId, sc.CrsNo });   // Configure a composite primary key for the StudentCourse entity using StudentId and CrsNo
            });
            modelBuilder.Entity<UserRole>(ur =>
            {
                ur.HasKey(u => new { u.UserId, u.Role });   // Configure a composite primary key for the UserRole entity using UserId and Role
            });
            // Seed Data for 5 Users
            modelBuilder.Entity<User>().HasData(
                new User { Id = 1, UserName = "AdminUser", UserEmail = "admin@iti.com", Password = "123" },
                new User { Id = 2, UserName = "Ali", UserEmail = "ali@iti.com", Password = "123" },
                new User { Id = 3, UserName = "Sara", UserEmail = "sara@iti.com", Password = "123" },
                new User { Id = 4, UserName = "Mona", UserEmail = "mona@iti.com", Password = "123" },
                new User { Id = 5, UserName = "Ahmed", UserEmail = "ahmed@iti.com", Password = "123" }
            );
            // Seed Data for User Roles
            modelBuilder.Entity<UserRole>().HasData(
                new UserRole { UserId = 1, Role = "Admin" },
                new UserRole { UserId = 2, Role = "Instructor" },
                new UserRole { UserId = 3, Role = "Student" },
                new UserRole { UserId = 4, Role = "Student" },
                new UserRole { UserId = 5, Role = "Instructor" }
            );
        }
        override protected void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source=.\\SQLEXPRESS;Initial Catalog=ITI_MVC;Integrated Security=True;TrustServerCertificate=True");   // Configure the database connection string to connect to a SQL Server database named "ITI" on the local machine using integrated security
            optionsBuilder.LogTo(Console.WriteLine, LogLevel.Information);
        }
    }
}
